UI components
Voviihb/FeedAndEat pull request #21
Opened 2024-04-05 21:47 UTC by 20alex20

implemented the basic elements, used them to design the home page and implemented mvvm for it

2024-04-06 06:32 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/data/models/CardDataModel.kt
> +)
Лучше перенести в домен

2024-04-06 06:32 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/data/repository/HomeRepository.kt
> +    }
Не понимаю, что это за функции. Возможно проблема в нейминге, а возможно они просто не нужны

2024-04-06 06:32 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/domain/repository/RecipeRepository.kt
> +
Убери

2024-04-06 06:32 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/domain/models/RecipeForm.kt
> +
Убери

2024-04-06 06:32 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreen.kt
> +        viewModel.getCardsTitle2()
Проверь как часто вызываются эти функции. Скорее всего они вызываются при каждой рекомпозиции.
Правильное решение унести их в init ViewModel

2024-04-06 06:32 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +            }
addAll

2024-04-06 09:29 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/Card.kt
> +        onClick = {}
Запиши в onClick /* TODO add function */
Так будет проще найти место, в котором не хватает каких-то функций. Студия эти TODO выделяет и кидает предупреждения при коммитах

2024-04-06 09:29 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/navigation/pres/NavBar.kt
>          mutableStateOf(MutableList(5) { 40 })
Это что? Откуда 40?

2024-04-07 16:38 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/navigation/pres/NavBar.kt
>          mutableStateOf(MutableList(5) { 40 })
Это Артем так хранит размеры иконок в навбаре. Вопрос снят

2024-04-07 17:20 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/RatingBar.kt
> -    color: Color = Color.Yellow
зачем кастомный цвет убрал?

2024-04-08 18:09 UTC, Voviihb requested changes

2024-04-08 18:09 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +
Наши экраны должны поддерживать состояние загрузки и ошибки (ошибку, кстати, нужно уметь сбрасывать. Как минимум, заготовь под это функцию, как у меня). Посмотри, как это сделано в моих VM. Моя реализация не является идеалом, но это лучше, чем ничего.

2024-04-08 18:09 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreen.kt
> +        viewModel.getCardsTitle2()
Подумай плз, может их реально стоит вытащить в блок init { } ?

2024-04-08 20:13 UTC, Voviihb requested changes

2024-04-08 20:13 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +    var largeCardData: CardDataModel by privateLargeCardData
Зачем? Было var largeCardData: State<CardDataModel> = privateLargeCardData и это было нормально

2024-04-08 20:13 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +    val errorMessage: Exception? by _errorMessage
Убери везде ... by ..., так не надо, верни как было через стейт
Раньше через State было правильно. Мы делаем внутри репозитория приватный mutableState, а наружу отдаем неизменяемый State, который ссылается на тот самый приватный изменяемый стейт

2024-04-08 20:13 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
>      var cardsDataOfRow3: List<CardDataModel> = privateCardsDataOfRow3
Лучше перейди на mutableStateOf(listOf< CardDataModel >())
Пример:
private val _recipesList = mutableStateOf(listOf<Recipe>())
val recipesList: State<List<Recipe>> = _recipesList

2024-04-08 20:25 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreen.kt
> +        viewModel.getCardsTitle2()
Перенес columnWidthDp во ViewModel (init не понадобился!, на его использование даже студия жалуется), LocalDencity.current требует вызова из @Composable

2024-04-08 20:26 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/RatingBar.kt
> -    color: Color = Color.Yellow
Вернул кастомный цвет

2024-04-08 20:26 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +
Добавил необходимые функции

2024-04-08 20:53 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +    var largeCardData: CardDataModel by privateLargeCardData
Во-первых, мне пришлось так сделать для columnWidthDp, потому что студия ругалась на ".value = ...". Поэтому аналогично сделал для остальных не List переменных
Во-вторых, это намного изящнее использовать State-переменную, как будто это обычная переменная

2024-04-08 20:54 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
>      var cardsDataOfRow3: List<CardDataModel> = privateCardsDataOfRow3
Опять же возвращаясь к тому как мы раньше делали

2024-04-08 21:22 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
>      var cardsDataOfRow3: List<CardDataModel> = privateCardsDataOfRow3
Я тут подумал, здесь ты абсолютно не прав. mutableStateListOf говорит о том, что будет происходить реакция на ЛЮБОЕ добавление/удаление элементов. А то что ты предлагаешь говорит о том, что будет реакция только на перезапись массива (НЕ НА ИЗМЕНЕНИЕ!!!), что в корне не правильно для viewModel.

2024-04-09 05:29 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
>      var cardsDataOfRow3: List<CardDataModel> = privateCardsDataOfRow3
Ты не понял. Приватная переменная остается изменяемой, ее ты меняешь внутри VM. А на неизменяемую подписываешься из экрана. Это один из примеров best-practice в компоузе)
Так, как сделано у меня, одобрено Максом. Так что переделывай

2024-04-09 05:30 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +    var largeCardData: CardDataModel by privateLargeCardData
Я понимаю, что так может быть удобнее, но так неправильно
Таковы реалии жизни

2024-04-09 05:31 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +    val errorMessage: Exception? by _errorMessage
by было уже на экране! В VM такого не было!

2024-04-09 05:33 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +    var largeCardData: CardDataModel by privateLargeCardData
На by переходи уже на экране, там реально это удобнее

2024-04-09 08:57 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +    var largeCardData: CardDataModel by privateLargeCardData
by на экране не работает из-за того что viewModel это val

2024-04-09 08:58 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +    val errorMessage: Exception? by _errorMessage
Кроме columnWidthDp by убрал везде

2024-04-09 08:58 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
>      var cardsDataOfRow3: List<CardDataModel> = privateCardsDataOfRow3
Переделал

2024-04-09 12:18 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/main/pres/HomeScreenViewModel.kt
> +    var largeCardData: CardDataModel by privateLargeCardData
Исправил

2024-04-09 12:21 UTC, Voviihb approved these changes

2024-04-09 14:58 UTC, merged