Adding db to viewmodels
Voviihb/FeedAndEat pull request #27
Opened 2024-04-08 19:02 UTC by Racher612

добавил базу в экран одного рецепта

2024-04-17 06:05 UTC, Voviihb requested changes

2024-04-17 06:05 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/BoxofText.kt
>              }
Или даже не так: если текста нет, то показывать что-то вроде "Ошибка!"?

2024-04-17 06:05 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                    textAlign = TextAlign.Center
Не стоит использовать !!, лучше если name = null, показать что-то вроде "Ошибка!"

2024-04-17 10:16 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                modifier = Modifier.padding(5.dp),
исправил

2024-04-17 10:16 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                    textAlign = TextAlign.Center
а почему у нас name нуллабельный кстати?

2024-04-17 16:03 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                    textAlign = TextAlign.Center
У нас все поля нуллабельные. Это особенность работы с сериализатором. Возможно, после фикса бага с nutrients, это будет изменено

2024-04-19 21:04 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                    textAlign = TextAlign.Center
Мы с тобой этот момент поправили, после merge с dev-ом убери !! здесь)

2024-04-22 15:01 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                    Color(red = 0x00, blue = 0xB6, green = 0xBB, alpha = 0xFF),
В моем файле это цвет dark_cyan, используй его

2024-04-22 15:02 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                .background(Color.Transparent),
Нафига прозрачный фон, если он и так есть у Text

2024-04-22 15:03 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                        .align(Alignment.CenterVertically),
у Text есть свои параметры позиционирования текста, не нужно юзать Modifier

2024-04-22 15:05 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                colors = ButtonColors(Color.White, Color.Gray, Color.White, Color.Black),
Цвета... Я могу часть не заметить сразу, но ты замени везде, потому что потом я опять проверю и найду их)

2024-04-22 15:07 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +        AsyncImage(
Я блин для кого DishImage делал?! Используй его (импортни его из dev, если нет его у тебя)

2024-04-22 15:10 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                Text(text = model.name!!,
Используй ?: для подстановки значения по умолчанию, юзать !! чтобы вылетать в ошибки плохая идея

2024-04-22 15:16 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +            .background(Color(red = 0xCF, blue = 0xFF, green = 0xFB))
pale_cyan у меня в цветах (я знаю что там вместо B написана С, но это максимально незначительное отличие)

2024-04-22 15:17 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +            Text(text = stringResource(R.string.ingridients) + " :" + ingredients?.size,
Если ты к строке прибавляешь null, будет ошибка. Обработай как-нибудь, например с помощью ?:

2024-04-22 15:18 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                    .padding(vertical = 10.dp),
Кратность 4

2024-04-22 15:18 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                    Color(red = 0xCF, blue = 0xFF, green = 0xFB, alpha = 0xFF),
pale_cyan в моих цветах

2024-04-22 15:19 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +            Text(text = stringResource(R.string.steps) + ": " + steps?.size,
Если ты к строке прибавляешь null, то может ошибки и не будет, но будет пустая строка. Обработай как-нибудь, например с помощью ?:

2024-04-22 15:20 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                .clip(shape = RoundedCornerShape(10.dp))
Кратность 4

2024-04-22 15:20 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +            .background(Color.Transparent),
Прозрачность, серьезно?

2024-04-22 15:20 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +            .padding(horizontal = 15.dp)
Кратность 4

2024-04-22 15:21 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +        Spacer(modifier = Modifier.height(10.dp))
Отступы кратны 4, а это отступ

2024-04-22 15:21 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                    Color(red = 0xE4, blue = 0xFE, green = 0xFA, alpha = 0xFF),
Это white_cyan у меня в цветах

2024-04-22 15:21 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                            .padding(start = 15.dp, end = 25.dp, top = 10.dp),
кратность 4

2024-04-22 15:22 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +            Spacer(modifier = Modifier.width(5.dp))
Кратность 4

2024-04-22 15:24 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +    val reload = {
Лучше вынеси в отельную функцию и передавай туда viewModel и id

2024-04-22 15:25 UTC, 20alex20 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/dishes/pres/RecipeScreen.kt
> +                    .align(Alignment.CenterVertically),
У Text есть свое позиционирование, используй его

2024-04-22 18:31 UTC, Voviihb approved these changes

2024-04-22 18:44 UTC, merged