single step screen
Voviihb/FeedAndEat pull request #43
Opened 2024-04-28 17:02 UTC by Racher612

2024-05-01 12:50 UTC, Voviihb requested changes

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/step/CongratulationsScreen.kt
> +//noinspection UsingMaterialAndMaterial3Libraries
убери

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/step/CongratulationsScreen.kt
> +//noinspection UsingMaterialAndMaterial3Libraries
убери

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/step/StepScreenViewModel.kt
> +        Log.d("CHANGE", "")
убери логи

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +//noinspection UsingMaterialAndMaterial3Libraries
зачем комментрировал?

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +//            modifier = Modifier.padding(vertical = 300.dp)
коммент

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +                contentDescription = "More"
убери в строковые ресурсы

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +                            "%02d:%02d:%02d",
тоже убери в ресурсы. посмотри, как я делал в сервисе, чтобы в строку из ресурсов подставить значения

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +                    if (timer.type == "constant") {
вытащи в ресурсы или в какой-то класс значение строки

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +                            "%02d:%02d:%02d - %02d:%02d:%02d",
в ресурсы строку

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +                        Log.d("OVER", "")
логи

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +    viewModel: StepScreenViewModel
почему не через hilt?

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +            text = String.format("%02d:%02d:%02d", hours, minutes, seconds),
ресурсы

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +            text = String.format("%02d:%02d:%02d", hours, minutes, seconds),
ресурсы

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +    val name = "${viewModel.name.value} - step ${viewModel.id.value}:"
в ресурсы

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +            if (timerList[currentTimer].type == "constant"){
в ресурсы или в какой-то класс

2024-05-01 12:50 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +//            val timerViewModel : TimerViewModel = hiltViewModel()
коммент

2024-05-04 17:05 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/step/CongratulationsScreen.kt
> +//noinspection UsingMaterialAndMaterial3Libraries
убрал

2024-05-04 17:05 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/step/CongratulationsScreen.kt
> +//noinspection UsingMaterialAndMaterial3Libraries
убрал

2024-05-04 17:05 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/step/StepScreenViewModel.kt
> +        Log.d("CHANGE", "")
убрал

2024-05-04 17:05 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +//noinspection UsingMaterialAndMaterial3Libraries
убрал

2024-05-04 17:06 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +//            modifier = Modifier.padding(vertical = 300.dp)
убрал

2024-05-04 17:09 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +            text = String.format("%02d:%02d:%02d", hours, minutes, seconds),
заменил

2024-05-04 17:09 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +    val name = "${viewModel.name.value} - step ${viewModel.id.value}:"
заменил

2024-05-04 17:16 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/timer/Timer.kt
> +            if (timerList[currentTimer].type == "constant"){
сделал класс состояний TimerTypes в Recipe.kt

2024-05-04 17:16 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/ExpandableElement.kt
> +//}
убрал

2024-05-04 17:16 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/ExpandableElement.kt
> +//}
точнее удалил весь файл

2024-05-04 17:24 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/navigation/data/NavGraph.kt
> +                destination = currentRoute ?: BottomScreen.InProgressScreen.route
теперь это nav_id

2024-05-04 17:24 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/navigation/pres/GlobalNavigationBar.kt
> +//noinspection UsingMaterialAndMaterial3Libraries
уже неактуально

2024-05-04 17:24 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/domain/TimerService.kt
>                  }
поменял

2024-05-04 17:51 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/domain/TimerService.kt
>              updateNotification()
невозможно безопасный вызов сделать

2024-05-04 17:51 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/domain/TimerService.kt
>              updateNotification()
+ таймер должен быть, раз мы его на паузу ставим

2024-05-04 17:52 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/domain/TimerService.kt
> +            val seconds = TimeUnit.SECONDS.toSeconds(timerValues[timerId]!!.remainingSec.toLong()) % 60
обезопасил

2024-05-04 17:52 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/domain/TimerService.kt
> +            val seconds = TimeUnit.SECONDS.toSeconds(timerValues[timerId]!!.remainingSec.toLong()) % 60
обезопасил

2024-05-04 17:52 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/step/StepScreenViewModel.kt
>          timerService.putExtra(
убрал

2024-05-04 18:48 UTC, Voviihb approved these changes

2024-05-05 09:05 UTC, merged