Feature login
Voviihb/FeedAndEat pull request #7
Opened 2024-03-10 17:19 UTC by Voviihb

2024-03-10 19:12 UTC, MoonLoone requested changes

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +                /* Email text field */
Лучше для отделения компонентов внутри экрана не пользоваться комментариями. Лучше выделяй подобное в отдельные функции

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +                                    text = errorMsg!!,
Лучше убрать !!

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +                        /* TODO is loading working? */
Доделать)

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +}
Разбей экраны на много маленьких функций. Одну функцию на 300+ строк читать и поддерживать очень тяжело

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/res/drawable/background_login.png
Написал в чате про пнг. Лучше переходите на векторы

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreenViewModel.kt
> +    private val EXCEPTION_OCCURRED = "Exception occurred!"
Хардкод

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreenViewModel.kt
> +    val errorMessage: State<String?> = _errorMessage
Я бы посоветовал объединить Loading и Error. Для этого можно выделить sealed interface, погугли

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreenViewModel.kt
> +    private val _auth: FirebaseAuth = Firebase.auth
Избавиться

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreenViewModel.kt
> +    val isUserAuthenticated get() = _authRepo.isUserAuthenticatedInFirebase()
Можно обойтись без этого. При удачной аутентификации просто сразу же переходить на новый экран

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreenViewModel.kt
> +                    Log.d("Taag", response.toString())
Логирвоание в master попадать не должно

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreenViewModel.kt
> +    }
То же, что для login

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/RegisterScreen.kt
> +    val (focusRequester) = FocusRequester.createRefs()
Скобки

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/RegisterScreen.kt
> +}
В целом по этому экрану те же правки, что по LoginScreen

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/RegisterScreenViewModel.kt
> +    private val PASSWORD_DIFFERS = "Passwords are not equal!"
Хардкод

2024-03-10 19:12 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/RegisterScreenViewModel.kt
> +}
Тут то же, что для LoginViewModel

2024-03-13 10:25 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +    }
Ладно

2024-03-13 10:26 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +        val roundValue = 12.dp
Переменная, отвечающая за радиус скругления у прямоугольников для формы ввода

2024-03-13 11:52 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +    val viewModel: LoginScreenViewModel = viewModel()
Потом

2024-03-13 12:01 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +    val (focusRequester) = FocusRequester.createRefs()
без скобок не работает

2024-03-13 16:09 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/data/AuthRepoImpl.kt
> +        }
Сделал

2024-03-13 16:09 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/data/AuthRepoImpl.kt
> +            }
Убрал

2024-03-13 16:17 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/data/AuthRepoImpl.kt
> +}
Все под одну функцию запихать не получилось, т.к. у них разный возвращаемый тип

2024-03-13 17:01 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
> +//            RegisterScreen(this)
убрал

2024-03-13 17:01 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
> -fun GreetingPreview() {
сейчас этого уже нет

2024-03-13 17:02 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/domain/models/LoginForm.kt
> +data class LoginForm(val email: String = "", val password: String = "")
Это для pres MVVM, переместил

2024-03-13 17:02 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/domain/models/RegisterForm.kt
> +)
Исправил, посмотри

2024-03-13 17:02 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/domain/repository/AuthRepository.kt
> +    suspend fun signOut(): Flow<Response<Boolean>>
исправил

2024-03-13 17:03 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +    }
Пока пусть будет так. Не совсем представляю, как сделать переход на другой экран иначе на текущий момент

2024-03-13 17:39 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +                /* Email text field */
Сделал

2024-03-13 18:29 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +                                    text = errorMsg!!,
убрал

2024-03-13 18:29 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +}
сделал

2024-03-13 18:30 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/RegisterScreen.kt
> +    val (focusRequester) = FocusRequester.createRefs()
без них не работает

2024-03-14 08:11 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/data/AuthRepoImpl.kt
> +    private val ERROR_MESSAGE: String = "Error"
Исправил

2024-03-14 08:12 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +        val roundValue = 12.dp
Это скругление используется в большом количестве элементов, поэтому вынес в отдельную переменную

2024-03-14 09:14 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/data/AuthRepoImpl.kt
> +}
Что-то такое подойдёт?
fun <ResponseItem> safeFlow(
        request: () -> ResponseItem
    ):Flow<Response<ResponseItem>> = flow { 
        try {
            emit(Response.Loading)
            val requestResult = request()
            emit(Response.Success(requestResult))
        }catch (e: Exception) {
            emit(Response.Failure(e))
        }
    }.flowOn(Dispatchers.IO)

2024-03-14 09:17 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +    val (focusRequester) = FocusRequester.createRefs()
Нельзя сделать?
val focusRequester = FocusRequester()

2024-03-14 09:18 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +    val (focusRequester) = FocusRequester.createRefs()
Либо val focusRequester = FocusRequester.createRefs().component1()

2024-03-14 09:19 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +        val roundValue = 12.dp
Так лучше не делать. Для элементов верстки лучше всё использовать индивидуально (не считая цветов и размеров шрифта)

2024-03-14 15:59 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +    val (focusRequester) = FocusRequester.createRefs()
исправил

2024-03-14 15:59 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/LoginScreen.kt
> +        val roundValue = 12.dp
исправил

2024-03-14 15:59 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/pres/RegisterScreen.kt
> +    val (focusRequester) = FocusRequester.createRefs()
исправил

2024-03-14 17:32 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/login/data/AuthRepoImpl.kt
> +}
готово

2024-03-14 18:10 UTC, MoonLoone approved these changes

2024-03-14 18:56 UTC, merged