Racher's branch 2
Voviihb/FeedAndEat pull request #8
Opened 2024-03-10 17:55 UTC by Racher612

0. Testing commits
1. Single Recipe

2024-03-10 18:46 UTC, MoonLoone requested changes

2024-03-10 18:46 UTC, MoonLoone commented on .idea/misc.xml
> +</project>
Нужно убрать ветку .idea из репозитория github. Для этого нужно внести изменения в файл .gitignore в корне проекта.

2024-03-10 18:46 UTC, MoonLoone commented on .idea/shelf/Uncommitted_changes_before_rebase_[Changes]/info.png
Вам стоит вместо png использовать векторные изображения, они имеют лучшее качество. Обсудите иконки с Александром.
Посмотри видео
https://www.youtube.com/watch?v=sQFWYm4B0Ck

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
>                  // A surface container using the 'background' color from the theme
Бесполезный комментарий

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
> +                    RecipeScreenViewModel(
Название вводит в заблуждение. Тут у тебя Composable функция, которая представляет экран. С viewModel это не имеет ничего общего

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
> +                        )
Все эти параметры нужно получать из viewModel

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
> +                    val steps = listOf("step 1", "step 2")
Все эти переменные нужно перенести в viewModel. А лучше сразу создавать репозитории и use cases для получения и манипуляции с данными. Посмотри как сделал Владимир или спроси у меня

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +import android.util.Log
Логи не должны попадать в master. Кроме специфичных вещей вроде запросов к локальной БД

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +val plug: () -> Unit = {Log.d("PLUG", "plug pressed")}
Что это?

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +    func: () -> Unit = plug
Дать понятное название переменной

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +val plug: () -> Unit = {Log.d("PLUG", "plug pressed")}
Если это только для тестов, то убрать

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +        shape = RoundedCornerShape(30.dp),
Размеры в андроид приложении должны быть кратны 8 или 4. Если ты брал размеры из фигмы, то наезжай на Алекандра)

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +        contentPadding = PaddingValues(0.dp),
Зачем ты указываешь нулевой падинг?

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +                    contentDescription = null,
Лучше делай описание. Люди с нарушением зрения будут недовольны таким твоим решением

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +fun infoSquareButton(
Composable должны быть с большой буквы

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +            .width(63.dp)
Размеры должны быть кратны 4 или 8

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +    func: () -> Unit = plug
Нужно значимое название

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +        contentPadding = PaddingValues(0.dp),
Зачем нулевые падинги?

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +            contentDescription = null,
null описание картинки

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +fun ComposeButton(text : String, fn:() -> Unit) {
название функции

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +            .border(2.dp, Color.Black, RoundedCornerShape(CornerSize(30.dp))),
размеры должны быть кратны 4 или 8

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +        contentPadding = PaddingValues(0.dp)
нулевой падинг

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +            // Your button text
Ненужный комментарий

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/RatingBar.kt
> +}
Проверить этот компонент для маленьких экранов, возможно тут будут проблемы

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/RatingBar.kt
> +fun RatingBarPreview(rating : Double) {
Если это превью, то лучше private

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/RatingBar.kt
> +}
Я не понимаю, что делает переменная. Мне также не нравится, что это глобальная переменная

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/RatingBar.kt
> +}
Я не понимаю, что делает переменная. Мне также не нравится, что это глобальная переменная

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/data/RecipeRepo.kt
> +    }
В репозитории не должно быть composable. 
Compose только для pres.

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/data/RecipeRepo.kt
> +    }
Также нельзя использовать на уровне данных Drawable и всё, что связано с context. 
Параметры функции должны писаться с маленькой буквы

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/res/values/strings.xml
> +    <string name="add_to_playlist">Добавить в подборку</string>
Playlist? Лучше придумать другое название

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +fun RecipeScreenViewModel(Picture : Int,
Тебе нужно научиться использовать viewModel. 
Изучи гайд гугл https://developer.android.com/codelabs/basic-android-kotlin-compose-viewmodel-and-state#0.

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +fun RecipeScreenViewModel(Picture : Int,
Дублирую, что название экрана не должно содержать ViewModel.

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +fun RecipeScreenViewModel(Picture : Int,
Если есть большой список параметров, то стоит подумать об dto

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    val pictureHeight = 310
Зачем эта переменная?

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +//    global container
Бесполезный коммент

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +//        container of rating
Бесполезный коммент

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +            contentDescription = null,
Пустое описание

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +fun RecipeScreenViewModel(Picture : Int,
Переменные функций пишут с маленькой буквы

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +//        Textfield
Бесполезный коммент. Если ты при помощи комментариев выделяешь основные компоненты экрана, то тебе стоит просто эти самые компоненты выделять в отдельные функции

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +            }
Зачем так. У тебя есть функция items(count){}

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +//                .background(Color.Yellow, shape = RoundedCornerShape(10.dp))
Убрать закомменченный код

2024-03-10 18:46 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    }
Слишком большая функция. Ты выделяешь при помощи комментариев отдельные компоненты экранов. Выдели их в отдельные функции, так код читается гораздо лучше

2024-03-16 11:19 UTC, Racher612 commented on .idea/misc.xml
> +</project>
Сделал

2024-03-16 11:21 UTC, Racher612 commented on .idea/shelf/Uncommitted_changes_before_rebase_[Changes]/info.png
В фиче над которой я сейчас работаю больше не используются png-изображения, а только vector assets
Однако в drawable старые png-картинки остались

2024-03-16 11:21 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
>                  // A surface container using the 'background' color from the theme
убрал

2024-03-16 11:22 UTC, MoonLoone commented on .idea/misc.xml
> +</project>
Ты добавил папку в gitignore. Нужно также убрать папку из репозитория

2024-03-16 11:22 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
> +                    RecipeScreenViewModel(
функция переименована в RecipePres;
Название файла осталось прежним, чтобы не нарушать общую архитектуру проекта

2024-03-16 11:22 UTC, MoonLoone commented on .idea/shelf/Uncommitted_changes_before_rebase_[Changes]/info.png
Что за старые картинки? Где они используются?

2024-03-16 11:30 UTC, Racher612 commented on .idea/shelf/Uncommitted_changes_before_rebase_[Changes]/info.png
Они нигде не используются. В целом их можно удалять

2024-03-16 11:33 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
> +                        )
я переделал чтобы эти параметры получались из RecipeRepo папки Data

2024-03-16 11:40 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +val plug: () -> Unit = {Log.d("PLUG", "plug pressed")}
это заглушка. она служит дефолтной функцией для всего, что принимает на вход () -> Unit.
Ну и заодно удобно что в консоль печатает

2024-03-16 11:41 UTC, Racher612 commented on .idea/shelf/Uncommitted_changes_before_rebase_[Changes]/info.png
удалил

2024-03-16 12:01 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +    func: () -> Unit = plug
BackArrowButton Пойдёт?

2024-03-16 12:03 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +        contentPadding = PaddingValues(0.dp),
В кнопке если не указывать нулевой паддинг происходит сильное сжатие контента внутри

2024-03-16 12:04 UTC, MoonLoone requested changes

2024-03-16 12:04 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +//    global container
Лишние комментарии

2024-03-16 12:04 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    }//end of global container
Лишний коммент

2024-03-16 12:04 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +            for (i in 0..(Description.size - 1)){
Всё ещё почему-то не используешь функцию items{}

2024-03-16 12:04 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    //Container which represents recipe description
Бесполезный комментарий. Можно дать значащее название для функции, если ты считаешь, что нужно дополнительное пояснение

2024-03-16 12:04 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +//        Buttons add to collection
Бесполезный комментарий. Можно дать значащее название для функции, если ты считаешь, что нужно дополнительное пояснение

2024-03-16 12:04 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    //        Info about Recipe + Start cooking
Бесполезный комментарий

2024-03-16 12:04 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    //    container for recipe name
Бесполезный комментарий

2024-03-16 12:04 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    //    extra container for back button & info
Бесполезный комментарий. Можно дать значащее название для функции, если ты считаешь, что нужно дополнительное пояснение. Если эта кнопка нужна не только для кнопки "назад", то ты обманул в названии функции

2024-03-16 12:04 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +                for (i in 0..names.size - 1){
Всё ещё нет items{}

2024-03-16 12:05 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +fun infoSquareButton(
исправил

2024-03-16 12:16 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +    func: () -> Unit = plug
Если честно, я не очень понимаю чем плохо название InfoSquareButton для квадратной кнопки с информацией

2024-03-16 12:29 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +fun ComposeButton(text : String, fn:() -> Unit) {
Ещё одна функция, которая не используется. Убрать

2024-03-16 12:31 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +    func: () -> Unit = plug
Я бы сделал SquareButton просто, чтобы не привязывать к конкретному элементу. И среди параметров добавил бы painter или resiurceId чтобы можно было использовать этот компонент для всех похожих элементов прост опередавая картинку

2024-03-16 15:24 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
> +                    RecipeScreenViewModel(
заменил название на RecipePres

2024-03-16 15:26 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +//        Textfield
убрал

2024-03-16 15:26 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +            contentDescription = null,
исправил

2024-03-16 15:27 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +            }
не очень понял суть вопроса

2024-03-16 15:27 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +//                .background(Color.Yellow, shape = RoundedCornerShape(10.dp))
убрал

2024-03-16 15:27 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    }
разбил на несколько функций

2024-03-16 15:28 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
> +                    recipeRepo.RecipeData()
убрал, теперь там одна функция

2024-03-16 15:28 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
> +                        .background(Color.Black),
убрал

2024-03-16 15:29 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/BoxofText.kt
> +//            .fillMaxHeight()
убрал

2024-03-16 15:30 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +//        Buttons add to collection
поменял на AddCollectionButtons

2024-03-16 15:30 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    //        Info about Recipe + Start cooking
убрал

2024-03-16 15:31 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    //    container for recipe name
убрал

2024-03-16 15:31 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    //    extra container for back button & info
убрал

2024-03-16 15:36 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +                for (i in 0..names.size - 1){
Исправил

2024-03-16 15:37 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/MainActivity.kt
> +                    val steps = listOf("step 1", "step 2")
на текущий момент данные берутся из ViewModel

2024-03-16 15:39 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +    func: () -> Unit = plug
Я бы предпочёл отказаться от такого решения в виду того, что размеры, окраска границ и прочие косметические штуки соответсвуют фигме. 
Такая кнопка "назад" используется не только в моём экране, и ребята смогут без проблем взять её для своих нужд при дальнейшей разработке.
Переименую в SquareArrowButton

2024-03-16 15:42 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +                    contentDescription = null,
исправил

2024-03-16 15:43 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +fun ComposeButton(text : String, fn:() -> Unit) {
убрал

2024-03-16 15:44 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +        shape = RoundedCornerShape(30.dp),
исправлено

2024-03-16 15:45 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +            contentDescription = null,
исправил

2024-03-16 15:45 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +        contentPadding = PaddingValues(0.dp),
В кнопке если не указывать нулевой паддинг происходит сильное сжатие контента внутри

2024-03-16 15:46 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +        contentPadding = PaddingValues(0.dp)
В кнопке если не указывать нулевой паддинг происходит сильное сжатие контента внутри

2024-03-16 15:46 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +            // Your button text
убрал

2024-03-16 15:50 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/RatingBar.kt
> +fun RatingBarPreview(rating : Double) {
Это не превью; поменял название на RatingBarPres

2024-03-16 15:53 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/RatingBar.kt
> +}
Код РейтингБара честно украден с просторов интернета, поэтому я затрудняюсь ответить на данный вопрос

2024-03-16 15:53 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/RatingBar.kt
> +}
пропущено

2024-03-16 15:55 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/RatingBar.kt
> +}
пропущено

2024-03-16 15:56 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/RatingBar.kt
> +}
пропущено

2024-03-16 15:59 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +            .width(63.dp)
исправлено

2024-03-16 15:59 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +            .border(2.dp, Color.Black, RoundedCornerShape(CornerSize(30.dp))),
исправил

2024-03-16 16:00 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/data/RecipeRepo.kt
> +    }
исправил

2024-03-16 16:02 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +    val pictureHeight = 310
отвечает за высоту картинки

2024-03-16 16:02 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +//    global container
согласен, убрал

2024-03-16 16:02 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +//        container of rating
убрал

2024-03-16 16:05 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CommonElements.kt
> +val plug: () -> Unit = {Log.d("PLUG", "plug pressed")}
убрал

2024-03-16 16:27 UTC, MoonLoone requested changes

2024-03-16 16:27 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/data/RecipeRepo.kt
> +    fun getRecipe() : RecipeForm {
Репозиторий не может возвращать объект-форму. Репозиторий предназначен для получения бизнес-объектов. Рецепты - да, теги - да. Формы - нет.

2024-03-16 16:27 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/domain/RecipeForm.kt
>  class RecipeForm {
Почему не data class?

2024-03-16 16:27 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +val LightBlue = Color(red = 0xCF, blue = 0xFF, green = 0xFC)
Глобальные переменные. Вам нужен объект Theme для определения основной палитры приложения

2024-03-16 16:27 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +    val surfaceWidth = 350
Не выделяй в переменную

2024-03-16 16:27 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +){
Параметры функций должны быть с маленькой буквы

2024-03-16 16:27 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +    Steps : List<String>
Параметры с большой буквы

2024-03-16 16:27 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +            for (i in 0..(Description.size - 1)){
items

2024-03-16 16:27 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +    Cooked : Int,
Параметры с большой буквы

2024-03-16 16:27 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +) {
Не должно быть в конструкторе этих параметров

2024-03-16 16:27 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +) {
Все эти данные должны получаться и храниться в ViewModel, привязанной к этому экрану

2024-03-16 16:27 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +fun RecipeScreenViewModel(){
ViewModel не может быть Composable. Ты не наследуешься от ViewModel. В общем, тут нужно переписывать все

2024-03-17 08:33 UTC, Voviihb commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +    Steps : List<String>
Исправь название параметров на маленькие буквы
А название compose функции - сделай с большой)

2024-03-18 19:17 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +    val surfaceWidth = 350
убрал

2024-03-18 19:17 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +){
исправил

2024-03-18 19:18 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +    Steps : List<String>
исправил

2024-03-18 19:21 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +            for (i in 0..(Description.size - 1)){
исправил

2024-03-18 19:21 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +    Cooked : Int,
исправил

2024-03-18 19:21 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipePres.kt
> +) {
исправил

2024-03-18 19:21 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/pres/RecipeScreenViewModel.kt
> +fun RecipeScreenViewModel(){
теперь ViewModel не компоузовская

2024-03-19 18:07 UTC, MoonLoone requested changes

2024-03-19 18:07 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/domain/repository/RecipeRepository.kt
> +}
Создал интерфейс, но не использовал

2024-03-19 18:07 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/ui/theme/Theme.kt
> +){
Что это?

2024-03-19 18:07 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/common/graphics/CustomCompose.kt
> +)
Все еще не убрал

2024-03-19 18:07 UTC, MoonLoone commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/domain/models/RecipeForm.kt
> +)
Зачем тебе форма? В чем ее отличие от RecypeDataModel?

2024-03-20 08:22 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/domain/repository/RecipeRepository.kt
> +}
убрал

2024-03-20 08:23 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/ui/theme/Theme.kt
> +){
убрал

2024-03-20 08:23 UTC, Racher612 commented on app/src/main/java/com/vk_edu/feed_and_eat/features/recipe/domain/models/RecipeForm.kt
> +)
убрал

2024-03-20 12:15 UTC, closed without merging

2024-03-20 12:15 UTC, MoonLoone commented
Теперь нужно вливать в dev